version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test-master:
    executor:
      name: node/default
    steps:
      - checkout
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - node/install-packages
            - run:
                command: npm run posttest
            - run:
                command: npm run test
  test-dev:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run posttest
      - run:
          command: npm run test

workflows:
  app-test:
    jobs:
      - test-dev
      - test-master
