version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test-master:
    executor:
      name: node/default
    steps:
      - checkout
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - node/install-packages
            - run:
                command: npm run test
  clean_db:
    executor:
      name: node/default
    steps:
      - node/install-packages
      - run:
          name: Clear test database
          command: npm run posttest

workflows:
  app-test:
    jobs:
      - clean_db
      - node/test:
          version: '16.10'
          pkg-manager: npm
          requires:
            - clean_db
      - test-master:
          requires:
            - clean_db
