version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test-master:
    executor:
      name: node/default
    steps:
      - checkout
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - checkout
            - node/install-packages
            - run:
                command: npm run test

workflows:
  app-test:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
      - test-master
